#!/bin/bash

# initial mac setup
# A lot of this is from https://github.com/mathiasbynens/dotfiles/blob/master/.osx

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# disable warning when changing file extensions
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# enable disk utility debug menu
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true

# enable text selection in quick look
defaults write com.apple.finder QLEnableTextSelection -boolean YES

# disable dashboard because it sucks
defaults write com.apple.dashboard mcx-disabled -boolean YES

# make the user library folder visible again
chflags nohidden ~/Library/

# stop preview from opening every PDF you've ever opened every time you view a PDF
# (how did apple think this was a good idea!?!?!)
defaults write com.apple.Preview NSQuitAlwaysKeepsWindows -bool false

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Increase sound quality for Bluetooth headphones/headsets
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Don’t show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true


# refresh stuff (killing will presumably make the watchdog restart the application)
killall Dock
killall Finder
killall SystemUIServer

# install xcode and xcode cli tools (large) or xcode cli tools (small)
# https://developer.apple.com/downloads/index.action

# install homebrew
test -x /usr/local/bin/brew || ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

brew update || exit 2
brew upgrade

# cli apps
brew install git nodejs tmux keychain picocom mcabber htop-osx autossh bash-completion gnu-sed coreutils ssh-copy-id mpd ncmpcpp mpc fish

# gui apps
brew tap phinze/homebrew-cask
brew install brew-cask
brew cask install adium alfred anvil app-cleaner arduino caffeine chocolat codekit cyberduck dropbox google-chrome handbrake iterm2 plex vlc

# iterm2 prefs
cp etc/com.googlecode.iterm2.plist ~/Library/Preferences/

# set default shell
if ! grep -q /usr/local/bin/fish /etc/shells; then
	echo Registering fish shell...
	echo /usr/local/bin/fish | sudo tee -a /etc/shells
fi
chsh -s /usr/local/bin/fish

# update completion db from man pages. OMGWOW.
/usr/local/bin/fish -c fish_update_completions


