#!/usr/bin/env bash
set -e

if [ "$EUID" -ne 0 ]; then
    echo "Run as root"
    exit 1
fi

if grep -q '^net.ipv4.ip_forward' /etc/sysctl.conf; then
    echo "Already configured, unsure of status. Please check."
    exit 1
fi

echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf

# reload
sysctl -p
